GO
CREATE TABLE [dbo].[Brands](
	[brandId] [smallint] IDENTITY(1,1) NOT NULL,
	[name] [varchar](64) NOT NULL,
 CONSTRAINT [PK_VehiclesBrands] PRIMARY KEY CLUSTERED 
(
	[brandId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]